### ISSUE TITLE
Does not work with TLS restrictions

### ISSUE THREAD

**Issue by toonetown** [hiltmon/Gist.tmbundle#13]
It appears that GitHub at some point in the past year or so stopped accepting SSLv2 and/or SSLv3 connections.  This makes the plugin not work at all anymore.

Any action (i.e. `Pick My Gists...`) returns the following:
```
/Users/me/Library/Application Support/TextMate/Managed/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:334:in `api_get_request': undefined method `code' for nil:NilClass (NoMethodError)
	from /Users/me/Library/Application Support/TextMate/Managed/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:414:in `get_login'
	from /Users/me/Library/Application Support/TextMate/Managed/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:80:in `pick'
	from Pick My Gists…:5
Received exception: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version

At line 586 in ‘http.rb’ (inside method ‘connect’)
At line 586 in ‘http.rb’ (inside method ‘connect’)
At line 553 in ‘http.rb’ (inside method ‘do_start’)
At line 542 in ‘http.rb’ (inside method ‘start’)
At line 1035 in ‘http.rb’ (inside method ‘request’)
At line 332 in ‘gistmate.rb’ (inside method ‘api_get_request’)
At line 38 in ‘progress.rb’ (inside method ‘call’)
At line 38 in ‘progress.rb’ (inside method ‘call_with_progress’)
At line 67 in ‘progress.rb’ (inside method ‘call’)
At line 67 in ‘progress.rb’ (inside method ‘call_with_progress’)
At line 22 in ‘ui.rb’ (inside method ‘dialog’)
At line 42 in ‘progress.rb’ (inside method ‘call_with_progress’)
At line 328 in ‘gistmate.rb’ (inside method ‘api_get_request’)
At line 414 in ‘gistmate.rb’ (inside method ‘get_login’)
At line 80 in ‘gistmate.rb’ (inside method ‘pick’)
At line 5 in ‘TextMate_command.TnXi5I’ (top level)
```

I am mostly reporting this for documentation purposes.  It doesn't appear this plugin is maintained much (last update was in 2014).  I plan to investigate how to update the script such that it will work with the server implementations, but if someone happens to get to it first, or knows a quick workaround, please add on here.

**Comment by quinncomendant** [comment]
@toonetown, did you ever update the script to fix this issue? I'm sure others, like myself, would benefit from your work. :)

**Comment by toonetown** [comment]
I haven’t - I was never able to figure out how to get it to work. 😕
